//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_web_app.CreateAccountService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CreateAccountService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/createAccount", ReplyAction="http://tempuri.org/IService1/createAccountResponse")]
        bool createAccount(string username, string password, string firstName, string lastName, string mobileNumber, string address, string jobProfile, string skills, string workExperience, string universityName, string cgpa, string degreeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/createAccount", ReplyAction="http://tempuri.org/IService1/createAccountResponse")]
        System.Threading.Tasks.Task<bool> createAccountAsync(string username, string password, string firstName, string lastName, string mobileNumber, string address, string jobProfile, string skills, string workExperience, string universityName, string cgpa, string degreeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/signIn", ReplyAction="http://tempuri.org/IService1/signInResponse")]
        bool signIn(string username, string password, bool isAdmin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/signIn", ReplyAction="http://tempuri.org/IService1/signInResponse")]
        System.Threading.Tasks.Task<bool> signInAsync(string username, string password, bool isAdmin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : final_web_app.CreateAccountService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<final_web_app.CreateAccountService.IService1>, final_web_app.CreateAccountService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool createAccount(string username, string password, string firstName, string lastName, string mobileNumber, string address, string jobProfile, string skills, string workExperience, string universityName, string cgpa, string degreeName) {
            return base.Channel.createAccount(username, password, firstName, lastName, mobileNumber, address, jobProfile, skills, workExperience, universityName, cgpa, degreeName);
        }
        
        public System.Threading.Tasks.Task<bool> createAccountAsync(string username, string password, string firstName, string lastName, string mobileNumber, string address, string jobProfile, string skills, string workExperience, string universityName, string cgpa, string degreeName) {
            return base.Channel.createAccountAsync(username, password, firstName, lastName, mobileNumber, address, jobProfile, skills, workExperience, universityName, cgpa, degreeName);
        }
        
        public bool signIn(string username, string password, bool isAdmin) {
            return base.Channel.signIn(username, password, isAdmin);
        }
        
        public System.Threading.Tasks.Task<bool> signInAsync(string username, string password, bool isAdmin) {
            return base.Channel.signInAsync(username, password, isAdmin);
        }
    }
}
